adds ramda to inso
otherwise, we get:
```
Run npm run test:smoke:cli

> insomnia@1.0.0 test:smoke:cli /home/runner/work/insomnia/insomnia
> npm run test:cli --prefix packages/insomnia-smoke-test

> insomnia-smoke-test@2.3.1 test:cli /home/runner/work/insomnia/insomnia/packages/insomnia-smoke-test
> npm run with-mock "npm run cli"

> insomnia-smoke-test@2.3.1 with-mock /home/runner/work/insomnia/insomnia/packages/insomnia-smoke-test
> concurrently --names server,app --success first --kill-others "npm run serve" "npm run cli"

[server]
[server] > insomnia-smoke-test@2.3.1 serve /home/runner/work/insomnia/insomnia/packages/insomnia-smoke-test
[server] > ts-node server/index.ts
[server]
[app]
[app] > insomnia-smoke-test@2.3.1 cli /home/runner/work/insomnia/insomnia/packages/insomnia-smoke-test
[app] > jest --detectOpenHandles --testPathPattern cli
[app]
[app] FAIL cli/app.test.ts
[app]   ● run test › can run unit test
[app]
[app]     Command failed with exit code 1: /home/runner/work/insomnia/insomnia/packages/insomnia-inso/bin/inso run test -a fixtures/inso-nedb TestSuite -e Dev
[app]
[app]      ERROR  Cannot find module 'ramda'
[app]     Require stack:
[app]     - /home/runner/work/insomnia/insomnia/packages/insomnia-send-request/dist/index.js
[app]     - /home/runner/work/insomnia/insomnia/packages/insomnia-inso/dist/index.js
[app]     - /home/runner/work/insomnia/insomnia/packages/insomnia-inso/bin/inso
[app]
[app]       Require stack:
[app]       - /home/runner/work/insomnia/insomnia/packages/insomnia-send-request/dist/index.js
[app]       - /home/runner/work/insomnia/insomnia/packages/insomnia-inso/dist/index.js
[app]       - /home/runner/work/insomnia/insomnia/packages/insomnia-inso/bin/inso
[app]
[app]       30487 | /***/ (function(module, exports) {
[app]       30488 |
[app]     > 30489 | module.exports = require("ramda");
[app]             |                  ^
[app]       30490 |
[app]       30491 | /***/ }),
[app]       30492 | /* 122 */
[app]
[app]       at Object.<anonymous> (../insomnia-send-request/dist/index.js:30489:18)
[app]       at __webpack_require__ (../insomnia-send-request/dist/index.js:21:30)
[app]       at Object.<anonymous> (../insomnia-send-request/dist/index.js:24042:17)
[app]       at __webpack_require__ (../insomnia-send-request/dist/index.js:21:30)
[app]       at Object.<anonymous> (../insomnia-send-request/dist/index.js:1308:31)
[app]       at __webpack_require__ (../insomnia-send-request/dist/index.js:21:30)
[app]       ℹ To view tracing information, re-run inso with --verbose
[app]       at makeError (node_modules/execa/lib/error.js:59:11)
[app]       at Function.Object.<anonymous>.module.exports.sync (node_modules/execa/index.js:186:17)
[app]       at Object.<anonymous> (cli/app.test.ts:9:30)
[app]
[app] Test Suites: 1 failed, 1 total
[app] Tests:       1 failed, 1 total
[app] Snapshots:   0 total
[app] Time:        1.915 s
```