ci failure mitigation
otherwise you get:

```console
$ npm run test:smoke:cli

> insomnia@1.0.0 test:smoke:cli /home/dimitri/src/github.com/Kong/insomnia
> npm run test:cli --prefix packages/insomnia-smoke-test

> insomnia-smoke-test@2.3.2 test:cli /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-smoke-test
> npm run with-mock "npm run cli"

> insomnia-smoke-test@2.3.2 with-mock /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-smoke-test
> concurrently --names server,app --success first --kill-others "npm run serve" "npm run cli"

[app]
[app] > insomnia-smoke-test@2.3.2 cli /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-smoke-test
[app] > jest --detectOpenHandles --testPathPattern cli
[app]
[server]
[server] > insomnia-smoke-test@2.3.2 serve /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-smoke-test
[server] > ts-node server/index.ts
[server]
[server] Listening at http://localhost:4010
[app]  FAIL  cli/app.test.ts
[app]   ● run test › can run unit test
[app]
[app]     Command failed with exit code 1: /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-inso/bin/inso run test -a fixtures/inso-nedb TestSuite -e Dev
[app]
[app]      WARN  The option --appDataDir has been deprecated and will be removed in future releases. Please use --src as an alternative
[app]
[app]
[app]      ERROR  Cannot find module 'ts-assert-unreachable'
[app]     Require stack:
[app]     - /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js
[app]     - /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-inso/dist/index.js
[app]     - /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-inso/bin/inso
[app]
[app]       Require stack:
[app]       - /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js
[app]       - /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-inso/dist/index.js
[app]       - /home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-inso/bin/inso
[app]       at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
[app]       at Function.Module._load (internal/modules/cjs/loader.js:841:27)
[app]       at Module.require (internal/modules/cjs/loader.js:1025:19)
[app]       at require (internal/modules/cjs/helpers.js:72:18)
[app]       at Object.<anonymous> (/home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js:29603:18)
[app]       at __webpack_require__ (/home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js:21:30)
[app]       at Object.<anonymous> (/home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js:767:33)
[app]       at Object.<anonymous> (/home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js:1291:30)
[app]       at __webpack_require__ (/home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js:21:30)
[app]       at Object.<anonymous> (/home/dimitri/src/github.com/Kong/insomnia/packages/insomnia-send-request/dist/index.js:1320:21)
[app]
[app]     ℹ To view tracing information, re-run inso with --verbose
[app]
[app]        7 |
[app]        8 |     // @ts-expect-error TSCONVERSION
[app]     >  9 |     const { failed } = execa.sync(getBinPathSync({ cwd: '../insomnia-inso' }), command.split(' '));
[app]          |                              ^
[app]       10 |
[app]       11 |     expect(failed).toBe(false);
[app]       12 |   });
[app]
[app]       at makeError (node_modules/execa/lib/error.js:59:11)
[app]       at Function.Object.<anonymous>.module.exports.sync (node_modules/execa/index.js:186:17)
[app]       at Object.<anonymous> (cli/app.test.ts:9:30)
[app]
[app] Test Suites: 1 failed, 1 total
[app] Tests:       1 failed, 1 total
[app] Snapshots:   0 total
[app] Time:        1.108 s
[app] Ran all test suites matching /cli/i.
[app] npm ERR! code ELIFECYCLE
[app] npm ERR! errno 1
[app] npm ERR! insomnia-smoke-test@2.3.2 cli: `jest --detectOpenHandles --testPathPattern cli`
[app] npm ERR! Exit status 1
```